use crate::cpu_fabric::CpuFabric;
use crate::halt_reason::{AtomicHaltReason, HaltReason, HaltReasonInner};
use crate::mmu::MMU;
use crate::sync::Mutex;

pub type VAddr = u64;

pub const PAGE_SIZE: VAddr = 4096;

// FIXME feature(const_convert)
#[allow(
    clippy::cast_possible_truncation,
    reason = "this function ensures no truncation happens"
)]
const fn u64_to_usize(int: u64) -> Option<usize> {
    match usize::BITS >= u64::BITS {
        true => Some(int as usize),
        false => {
            // widening cast
            let max = usize::MAX as u64;
            if int > max {
                return None
            }
            Some(PAGE_SIZE as usize)
        },
    }
}

pub(crate) mod sealed {
    use std::sync::atomic::AtomicU8;
    use crate::a64::{u64_to_usize, PAGE_SIZE};
    use crate::{cpu_fabric, vaddr};
    use crate::mmu::{MemoryFault, PageFlags, MMU};

    #[derive(Copy, Clone, Eq, PartialEq, Hash)]
    pub enum ExclusiveMonitorLoad {
        U128(u128),
        U64(u64),
        U32(u32),
        U16(u16),
        U8(u8),
    }


    // https://developer.arm.com/documentation/ddi0487/maa/-Part-B-The-AArch64-Application-Level-Architecture/-Chapter-B2-The-AArch64-Application-Level-Memory-Model/-B2-2-Atomicity-in-the-Arm-architecture/-B2-2-1-Requirements-for-single-copy-atomicity

    // B2.2.1 Requirements for single-copy atomicity
    // For explicit memory effects generated from an Exception level the following rules apply:
    //
    // * A read that is generated by a load instruction that loads
    //   a single general-purpose register and is aligned to the size
    //   of the read in the instruction is single-copy atomic.
    //
    // * A write that is generated by a store instruction that stores a single general-purpose
    //   register and is aligned to the size of the write in the
    //   instruction is single-copy atomic.
    //
    // * Reads that are generated by a Load Pair instruction that loads two general-purpose
    //   registers and are aligned to the size of the load to each register are treated
    //   as two single-copy atomic reads, one for each register being loaded.
    //
    // * Writes that are generated by a Store pair instruction that stores two general-purpose
    //   registers and are aligned to the size of the store of each register are treated as two
    //   single-copy atomic writes, one for each register being stored.
    //
    // * Load-Exclusive Pair instructions of two 32-bit quantities and Store-Exclusive
    //   Pair instructions of 32-bit quantities are single-copy atomic.
    //
    // * When the Store-Exclusive of a Load-Exclusive/Store-Exclusive pair instruction
    //   using two 64-bit quantities succeeds, it causes a single-copy atomic update
    //   of the entire memory location being updated.
    //
    // # Note
    // To atomically load two 64-bit quantities, perform a Load-Exclusive pair/Store-Exclusive
    // pair sequence of reading and writing the same value for which the Store-Exclusive pair
    // succeeds, and use the read values from the Load-Exclusive pair.
    //
    // * Where translation table walks generate a read of a translation table entry,
    //   this read is single-copy atomic.
    //
    // * For the atomicity of instruction fetches, see Concurrent modification
    //   and execution of instructions.
    //
    // * Reads to SIMD and floating-point registers of a single 64-bit or smaller quantity
    //   that is aligned to the size of the quantity being loaded are treated as single-copy
    //   atomic reads.
    //
    // * Writes from SIMD and floating-point registers of a single 64-bit or smaller quantity
    //   that is aligned to the size of the quantity being stored are treated as single-copy
    //   atomic writes.
    //
    // * Element or Structure Reads to SIMD and floating-point registers of 64-bit
    //   or smaller elements, where each element is aligned to the size of the element
    //   being loaded, have each element treated as a single-copy atomic read.
    //
    // * Element or Structure Writes from SIMD and floating-point registers of 64-bit
    //   or smaller elements, where each element is aligned to the size of the element
    //   being stored, have each element treated as a single-copy atomic store.
    //
    // * Reads to SIMD and floating-point registers of a 128-bit value that is 64-bit
    //   aligned in memory are treated as a pair of single-copy atomic 64-bit reads.
    //
    // * Writes from SIMD and floating-point registers of a 128-bit value
    //   that is 64-bit aligned in memory are treated as a pair of single-copy
    //   atomic 64-bit writes.
    //
    // * If FEAT_LS64WB is implemented, accesses to two 128-bit SIMD and floating-point
    //   registers by an LDP (SIMD&FP) or STP (SIMD&FP) instruction are treated as one
    //   single-copy atomic 256-bit access when both the following are true:
    //
    // * The access is 32-byte aligned in memory.
    //
    // * The access is to Normal Inner Write-Back, Outer Write-Back Cacheable, Shareable memory.
    //
    // * SVE predicated load and store instructions have the same single-copy
    //   atomicity guarantees as the SIMD load and store instructions for 64-bit
    //   or smaller elements.
    //
    // * An SVE predicated load or store of a 128-bit element that is 64-bit aligned
    //   is treated as a pair of 64-bit single-copy atomic accesses.
    //
    // * SVE unpredicated load and store instructions
    //   are performed as a sequence of byte accesses.
    //
    // * SVE unpredicated load and store instructions do not guarantee that any access larger
    //   than a byte will be performed as a single-copy atomic access.
    //
    // * When FEAT_LS64 is implemented, a single-copy atomic load of a 64-byte
    //   value that is 64-byte aligned in memory is treated as an atomic 64-byte
    //   read from the target address.
    //
    // * When FEAT_LS64 is implemented, a single-copy atomic store of a 64-byte value
    //   that is 64-byte aligned in memory is treated as an atomic 64-byte write
    //   to the target address.
    //
    // * For unaligned memory accesses, the single-copy atomicity is described in Alignment
    //   of data accesses.
    //
    // * The read and write generated by an Atomic instruction is single-copy atomic at the
    //   overall size of the data access.
    #[allow(
        clippy::cast_possible_truncation,
        reason = "all truncation here is actually handled,\
                  it used to split up one large integer to a bunch of smaller ones"
    )]
    mod memops {
        // FIXME: currently, this is UB, it just happens to work for rust 1.95.0,
        //        but mixed sized atomic access is UB, and I am explictly doing UB
        //        if it ever stops being UB, thats GREAT, otherwise, this needs to be fixed

        use std::hint::cold_path;
        use std::sync::atomic::{AtomicU8, AtomicU16, AtomicU32, AtomicU64, Ordering};

        #[inline(always)]
        pub(crate) unsafe fn load64_le_aligned(ptr: *const AtomicU8) -> u64 {
            unsafe { (*ptr.cast::<AtomicU64>()).load(Ordering::Relaxed).to_le() }
        }

        #[inline(always)]
        pub(crate) unsafe fn store64_le_aligned(ptr: *const AtomicU8, value: u64) {
            unsafe { (*ptr.cast::<AtomicU64>()).store(value.to_le(), Ordering::Relaxed) }
        }

        #[inline(always)]
        pub(crate) unsafe fn load32_le_aligned(ptr: *const AtomicU8) -> u32 {
            unsafe { (*ptr.cast::<AtomicU32>()).load(Ordering::Relaxed).to_le() }
        }

        #[inline(always)]
        pub(crate) unsafe fn store32_le_aligned(ptr: *const AtomicU8, value: u32) {
            unsafe { (*ptr.cast::<AtomicU32>()).store(value.to_le(), Ordering::Relaxed) }
        }

        #[inline(always)]
        pub(crate) unsafe fn load16_le_aligned(ptr: *const AtomicU8) -> u16 {
            unsafe { (*ptr.cast::<AtomicU16>()).load(Ordering::Relaxed).to_le() }
        }

        #[inline(always)]
        pub(crate) unsafe fn store16_le_aligned(ptr: *const AtomicU8, value: u16) {
            unsafe { (*ptr.cast::<AtomicU16>()).store(value.to_le(), Ordering::Relaxed) }
        }

        #[inline(always)]
        pub(crate) unsafe fn load_8_unaligned(ptr: *const AtomicU8) -> u8 {
            const { assert!(align_of::<AtomicU8>() == 1) }

            unsafe { (*ptr).load(Ordering::Relaxed) }
        }

        #[inline(always)]
        pub(crate) unsafe fn store_8_unaligned(ptr: *const AtomicU8, value: u8) {
            const { assert!(align_of::<AtomicU8>() == 1) }

            unsafe { (*ptr).store(value, Ordering::Relaxed) }
        }



        // Unaligned 64-bit little-endian access patterns:
        //
        // addr % 8 == 4:
        //   alignment:
        //     addr % 4 == 0
        //     addr + 4 is aligned to 8 and still aligned to 4
        //   layout:
        //     ptr: b0 b1 b2 b3 b4 b5 b6 b7
        //          └───lo────┘ └────hi───┘
        //     value = (hi << 32) | lo
        //   accesses exactly:
        //     [ptr + 0, ptr + 4)
        //     [ptr + 4, ptr + 8)
        //
        // addr % 8 == 2 or 6:
        //   alignment:
        //     addr is aligned to 2
        //     addr + 2 is aligned to 4
        //     addr + 6 is aligned to 2
        //   layout:
        //     ptr: b0 b1 b2 b3 b4 b5 b6 b7
        //          └w0─┘ └───mid───┘ └w3─┘
        //     value = (hi << 48) | (mid << 16) | lo
        //   accesses exactly:
        //     [ptr + 0, ptr + 2)
        //     [ptr + 2, ptr + 6)
        //     [ptr + 6, ptr + 8)
        //
        // addr % 8 == 1 or 5:
        //   alignment:
        //     addr is not aligned to 2
        //     addr + 1 is aligned to 2
        //     addr + 3 is aligned to 4
        //     addr + 7 is loaded/stored as one byte
        //   layout:
        //     ptr: b0 b1 b2 b3 b4 b5 b6 b7
        //          │  └w1─┘ └───mid───┘  │
        //          b0                    b7
        //     value = (b7 << 56) | (mid << 24) | (w1 << 8) | b0
        //   accesses exactly:
        //     [ptr + 0, ptr + 1)
        //     [ptr + 1, ptr + 3)
        //     [ptr + 3, ptr + 7)
        //     [ptr + 7, ptr + 8)
        //
        // addr % 8 == 3 or 7:
        //   alignment:
        //     addr is not aligned to 2
        //     addr + 1 is aligned to 4
        //     addr + 5 is aligned to 2
        //     addr + 7 is loaded/stored as one byte
        //   layout:
        //     ptr: b0 b1 b2 b3 b4 b5 b6 b7
        //          │  └───mid───┘ └w5─┘  │
        //          b0                    b7
        //     value = (b7 << 56) | (w5 << 40) | (mid << 8) | b0
        //   accesses exactly:
        //     [ptr + 0, ptr + 1)
        //     [ptr + 1, ptr + 5)
        //     [ptr + 5, ptr + 7)
        //     [ptr + 7, ptr + 8)


        #[inline(always)]
        pub(super) unsafe fn load64_le(ptr: *const AtomicU8) -> u64 {
            const { assert!(align_of::<AtomicU64>() == 8) }

            match ptr.addr() % 8 {
                0 => unsafe { load64_le_aligned(ptr) },

                4 => unsafe {
                    cold_path();

                    let lo = load32_le_aligned(ptr) as u64;
                    let hi = load32_le_aligned(ptr.byte_add(4)) as u64;

                    (hi << 32) | lo
                }

                2 | 6 => unsafe {
                    cold_path();

                    let lo = load16_le_aligned(ptr) as u64;
                    let mid = load32_le_aligned(ptr.byte_add(2)) as u64;
                    let hi = load16_le_aligned(ptr.byte_add(6)) as u64;

                    (hi << 48) | (mid << 16) | lo
                }

                1 | 5 => unsafe {
                    cold_path();

                    let b0 = load_8_unaligned(ptr) as u64;
                    let w1 = load16_le_aligned(ptr.byte_add(1)) as u64;
                    let mid = load32_le_aligned(ptr.byte_add(3)) as u64;
                    let b7 = load_8_unaligned(ptr.byte_add(7)) as u64;

                    (b7 << 56) | (mid << 24) | (w1 << 8) | b0
                }

                3 | 7 => unsafe {
                    cold_path();

                    let b0 = load_8_unaligned(ptr) as u64;
                    let mid = load32_le_aligned(ptr.byte_add(1)) as u64;
                    let w5 = load16_le_aligned(ptr.byte_add(5)) as u64;
                    let b7 = load_8_unaligned(ptr.byte_add(7)) as u64;

                    (b7 << 56) | (w5 << 40) | (mid << 8) | b0
                }
                _ => unsafe { core::hint::unreachable_unchecked() }
            }
        }

        #[inline(always)]
        pub(super) unsafe fn store64_le(ptr: *const AtomicU8, value: u64) {
            const { assert!(align_of::<AtomicU64>() == 8) }

            match ptr.addr() % 8 {
                0 => unsafe { store64_le_aligned(ptr, value) },

                4 => unsafe {
                    cold_path();

                    let lo = value as u32;
                    let hi = (value >> 32) as u32;

                    store32_le_aligned(ptr, lo);
                    store32_le_aligned(ptr.byte_add(4), hi);
                }

                2 | 6 => unsafe {
                    cold_path();

                    let lo = value as u16;
                    let mid = (value >> 16) as u32;
                    let hi = (value >> 48) as u16;

                    store16_le_aligned(ptr, lo);
                    store32_le_aligned(ptr.byte_add(2), mid);
                    store16_le_aligned(ptr.byte_add(6), hi);
                }

                1 | 5 => unsafe {
                    cold_path();

                    let b0 = value as u8;
                    let w1 = (value >> 8) as u16;
                    let mid = (value >> 24) as u32;
                    let b7 = (value >> 56) as u8;

                    store_8_unaligned(ptr, b0);
                    store16_le_aligned(ptr.byte_add(1), w1);
                    store32_le_aligned(ptr.byte_add(3), mid);
                    store_8_unaligned(ptr.byte_add(7), b7);
                }

                3 | 7 => unsafe {
                    cold_path();

                    let b0 = value as u8;
                    let mid = (value >> 8) as u32;
                    let w5 = (value >> 40) as u16;
                    let b7 = (value >> 56) as u8;

                    store_8_unaligned(ptr, b0);
                    store32_le_aligned(ptr.byte_add(1), mid);
                    store16_le_aligned(ptr.byte_add(5), w5);
                    store_8_unaligned(ptr.byte_add(7), b7);
                }

                _ => unsafe { core::hint::unreachable_unchecked() }
            }
        }





        // Unaligned 32-bit little-endian access patterns:
        //
        // addr % 4 == 2:
        //   alignment:
        //     addr is aligned to 2
        //     addr + 2 is aligned to 4 and still aligned to 2
        //   layout:
        //     ptr: b0 b1 b2 b3
        //          └lo─┘ └─hi┘
        //     value = (hi << 16) | lo
        //   accesses exactly:
        //     [ptr + 0, ptr + 2)
        //     [ptr + 2, ptr + 4)
        //
        // addr % 4 == 1 or 3:
        //   alignment:
        //     addr is not aligned to 2
        //     addr + 1 is aligned to 2
        //     addr + 3 is loaded/stored as one byte
        //   layout:
        //     ptr: b0 b1 b2 b3
        //          │  └mid┘  │
        //          b0        b3
        //     value = (b3 << 24) | (mid << 8) | b0
        //   accesses exactly:
        //     [ptr + 0, ptr + 1)
        //     [ptr + 1, ptr + 3)
        //     [ptr + 3, ptr + 4)


        #[inline(always)]
        pub(crate) unsafe fn load32_le(ptr: *const AtomicU8) -> u32 {
            const { assert!(align_of::<AtomicU32>() == 4) }

            match ptr.addr() % 4 {
                0 => unsafe { load32_le_aligned(ptr) },

                2 => unsafe {
                    cold_path();

                    let lo = load16_le_aligned(ptr) as u32;
                    let hi = load16_le_aligned(ptr.byte_add(2)) as u32;

                    (hi << 16) | lo
                }

                1 | 3 => unsafe {
                    cold_path();

                    let b0 = load_8_unaligned(ptr) as u32;
                    let mid = load16_le_aligned(ptr.byte_add(1)) as u32;
                    let b3 = load_8_unaligned(ptr.byte_add(3)) as u32;

                    (b3 << 24) | (mid << 8) | b0
                }

                _ => unsafe { core::hint::unreachable_unchecked() }
            }
        }

        #[inline(always)]
        pub(crate) unsafe fn store32_le(ptr: *const AtomicU8, value: u32) {
            const { assert!(align_of::<AtomicU32>() == 4) }

            match ptr.addr() % 4 {
                0 => unsafe { store32_le_aligned(ptr, value) },

                2 => unsafe {
                    cold_path();

                    let lo = value as u16;
                    let hi = (value >> 16) as u16;

                    store16_le_aligned(ptr, lo);
                    store16_le_aligned(ptr.byte_add(2), hi);
                }

                1 | 3 => unsafe {
                    cold_path();

                    let b0 = value as u8;
                    let mid = (value >> 8) as u16;
                    let b3 = (value >> 24) as u8;

                    store_8_unaligned(ptr, b0);
                    store16_le_aligned(ptr.byte_add(1), mid);
                    store_8_unaligned(ptr.byte_add(3), b3);
                }

                _ => unsafe { core::hint::unreachable_unchecked() }
            }
        }



        // Unaligned 16-bit little-endian access pattern:
        //
        // addr % 2 == 1:
        //   alignment:
        //     both bytes are loaded/stored as single bytes, so alignment is always ok
        //   layout:
        //     ptr: b0 b1
        //          │  │
        //          b0 b1
        //     value = (b1 << 8) | b0
        //   accesses exactly:
        //     [ptr + 0, ptr + 1)
        //     [ptr + 1, ptr + 2)


        #[inline(always)]
        pub(crate) unsafe fn load16_le(ptr: *const AtomicU8) -> u16 {
            const { assert!(align_of::<AtomicU16>() == 2) }

            match ptr.addr() % 2 {
                0 => unsafe { load16_le_aligned(ptr) },

                1 => unsafe {
                    cold_path();

                    let b0 = load_8_unaligned(ptr) as u16;
                    let b1 = load_8_unaligned(ptr.byte_add(1)) as u16;

                    (b1 << 8) | b0
                }

                _ => unsafe { core::hint::unreachable_unchecked() },
            }
        }

        #[inline(always)]
        pub(crate) unsafe fn store16_le(ptr: *const AtomicU8, value: u16) {
            const { assert!(align_of::<AtomicU16>() == 2) }

            match ptr.addr() % 2 {
                0 => unsafe { store16_le_aligned(ptr, value) },

                1 => unsafe {
                    cold_path();

                    store_8_unaligned(ptr, value as u8);
                    store_8_unaligned(ptr.byte_add(1), (value >> 8) as u8);
                }

                _ => unsafe { core::hint::unreachable_unchecked() },
            }
        }

        #[inline(always)]
        pub(crate) unsafe fn load8(ptr: *const AtomicU8) -> u8 {
            unsafe { load_8_unaligned(ptr) }
        }

        #[inline(always)]
        pub(crate) unsafe fn store8(ptr: *const AtomicU8, value: u8) {
            unsafe { store_8_unaligned(ptr, value) }
        }
    }

    unsafe impl vaddr::sealed::VAddr for u64 {
        const NULL: Self = 0;
        const PAGE_SIZE: usize = u64_to_usize(PAGE_SIZE).unwrap();
        const PAGE_SIZE_SELF: Self = PAGE_SIZE;

        type InsnWord = u32;
        type ExclusiveMonitorLoadValue = ExclusiveMonitorLoad;

        fn reservation_index(self) -> usize {
            let mut x = self;
            x ^= x >> 30;
            x = x.wrapping_mul(0xbf58_476d_1ce4_e5b9);
            x ^= x >> 27;
            x = x.wrapping_mul(0x94d0_49bb_1331_11eb);
            x ^= x >> 31;

            let bucket_count: u16 = cpu_fabric::BUCKET_COUNT;

            #[allow(
                clippy::cast_possible_truncation,
                reason = "bucket count is u16, so x mod u16 fits in u16"
            )]
            let index = x.strict_rem(u64::from(bucket_count)) as u16;

            usize::from(index)
        }

        fn add_addr(self, other: Self) -> Option<Self> {
            self.checked_add(other)
        }

        fn add_offset(self, other: usize) -> Option<Self> {
            self.checked_add(u64::try_from(other).ok()?)
        }

        fn is_multiple_of(self, rhs: Self) -> bool {
            self.is_multiple_of(rhs)
        }

        fn try_to_usize(self) -> Option<usize> {
            u64_to_usize(self)
        }

        fn div_rem_page_size(self) -> (Self, usize) {
            let div = self / PAGE_SIZE;
            // PAGE_SIZE fits in a usize, so x mod PAGE_SIZE must fit in usize
            let offset = (self % PAGE_SIZE) as usize;
            (div, offset)
        }

        unsafe fn div_page_size_unchecked(self) -> Self {
            let (div, rem) = self.div_rem_page_size();
            unsafe { core::hint::assert_unchecked(rem == 0) }
            div
        }

        fn fetch_insn_word(self, mmu: &MMU<Self>) -> Result<Self::InsnWord, MemoryFault> {
            let value = unsafe {
                // Safety: no store will happen
                let (page, offset) = mmu.single_page_aligned_access::<4>(self)?;
                let ptr = page.get_data_ptr(PageFlags::EXECUTE)?;
                memops::load32_le_aligned(ptr.as_ptr().byte_add(offset))
            };

            Ok(value)
        }

        unsafe fn load64_le(ptr: *const AtomicU8) -> u64 {
            unsafe { memops::load64_le(ptr) }
        }

        unsafe fn store64_le(ptr: *const AtomicU8, value: u64) {
            unsafe { memops::store64_le(ptr, value) }
        }

        unsafe fn load32_le(ptr: *const AtomicU8) -> u32 {
            unsafe { memops::load32_le(ptr) }
        }

        unsafe fn store32_le(ptr: *const AtomicU8, value: u32) {
            unsafe { memops::store32_le(ptr, value) }
        }

        unsafe fn load16_le(ptr: *const AtomicU8) -> u16 {
            unsafe { memops::load16_le(ptr) }
        }

        unsafe fn store16_le(ptr: *const AtomicU8, value: u16) {
            unsafe { memops::store16_le(ptr, value) }
        }



        unsafe fn load64_le_aligned(ptr: *const AtomicU8) -> u64 {
            unsafe { memops::load64_le_aligned(ptr) }
        }

        unsafe fn store64_le_aligned(ptr: *const AtomicU8, value: u64) {
            unsafe { memops::store64_le_aligned(ptr, value) }
        }

        unsafe fn load32_le_aligned(ptr: *const AtomicU8) -> u32 {
            unsafe { memops::load32_le_aligned(ptr) }
        }

        unsafe fn store32_le_aligned(ptr: *const AtomicU8, value: u32) {
            unsafe { memops::store32_le_aligned(ptr, value) }
        }

        unsafe fn load16_le_aligned(ptr: *const AtomicU8) -> u16 {
            unsafe { memops::load16_le_aligned(ptr) }
        }

        unsafe fn store16_le_aligned(ptr: *const AtomicU8, value: u16) {
            unsafe { memops::store16_le_aligned(ptr, value) }
        }
        
        
        unsafe fn load_byte(ptr: *const AtomicU8) -> u8 {
            unsafe { memops::load8(ptr) }
        }

        unsafe fn store_byte(ptr: *const AtomicU8, value: u8) {
            unsafe { memops::store8(ptr, value) }
        }
    }
}


#[derive(bytemuck::Pod, bytemuck::Zeroable, Copy, Clone)]
#[repr(C, align(16))]
pub struct Vector(pub u128);

const _: () = assert!(align_of::<Vector>() == 16 && size_of::<Vector>() == 16);

#[repr(C)]
struct ExecutingData {
    sp: u64,
    pc: u64,
    x_registers: [u64; 31],
    pstate: u32,
    fpsr: u32,
    fpcr: u32,
    vectors: [Vector; 32],
}

impl ExecutingData {
    fn clear_instruction_cache(&mut self) {
        todo!("invalidate instruction cache")
    }
}

pub struct Arm64CpuCore {
    mmu: MMU<VAddr>,
    fabric: CpuFabric<VAddr>,
    halt_reason: AtomicHaltReason,
    executing: Mutex<ExecutingData>,
}

impl Arm64CpuCore {
    pub fn new(mmu: MMU<VAddr>, fabric: CpuFabric<VAddr>) -> Self {
        Self {
            mmu,
            fabric,
            halt_reason: AtomicHaltReason::new(HaltReasonInner::empty()),
            executing: Mutex::new(const {
                ExecutingData {
                    sp: 0,
                    pc: 0,
                    x_registers: [0; 31],
                    pstate: 0,
                    fpsr: 0,
                    fpcr: 0,
                    vectors: [Vector(0); 32],
                }
            })
        }
    }

    pub fn mmu(&self) -> &MMU<VAddr> {
        &self.mmu
    }

    pub fn mmu_mut(&mut self) -> &mut MMU<VAddr> {
        &mut self.mmu
    }

    #[track_caller]
    fn execute(
        &self,
        fun: impl FnMut(&mut ExecutingData) -> HaltReasonInner
    ) -> HaltReason {
        let Some(mut lock) = self.executing.try_lock() else {
            panic!("the CPU is already executing")
        };

        let data: &mut ExecutingData = &mut lock;
        let mut fun = fun;
        loop {
            let halt_reason = fun(data);

            if halt_reason.contains(HaltReasonInner::InvalidateInstructionCache) {
                data.clear_instruction_cache();
                // if we only halted because we had InvalidateInstructionCache
                if (halt_reason ^ HaltReasonInner::InvalidateInstructionCache).is_empty() {
                    continue
                }
            }

            break HaltReason::from_inner(halt_reason)
        }
    }

    /// Runs the emulated CPU.
    /// Cannot be recursively called.
    pub fn run(&self) -> HaltReason {
        todo!()
    }

    /// Step the emulated CPU for one instruction.
    /// Cannot be recursively called.
    pub fn step(&self) -> HaltReason {
        todo!()
    }

    pub fn halt(&self, reason: HaltReason) {
        self.halt_reason.add_reasons(reason.into_inner())
    }
}
